# Only for development purposes
name: webcanape-birthday

services:
  php:
    build: ./php
    volumes:
      - ../:/app
      - ../.runtime/cache/composer:/.composer/cache
      - ../.runtime/logs/php:/var/log/php
    user: $USER_ID:$GROUP_ID
    working_dir: /app
    depends_on:
      - mariadb

  cron:
    build: ./cron
    working_dir: /app
    user: $USER_ID:$GROUP_ID
    volumes:
      - ../:/app
      - ../.runtime/logs/cron:/var/log/cron

  queue:
    build: ./queue
    volumes:
      - ../:/app
      - ../.runtime/cache/composer:/.composer/cache
      - ../.runtime/logs/php:/var/log/php
    user: $USER_ID:$GROUP_ID
    working_dir: /app
    depends_on:
      - mariadb
    command: sh -c "php artisan queue:work"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    working_dir: /app
    ports:
      - 80:80

  mariadb:
    image: mariadb:11.3
    volumes:
      - ../.runtime/mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: ${DB_DATABASE}
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 1G
    ports:
      - 8080:80
    depends_on:
      - mariadb
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php:ro
